logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
---
createdb:
  logins:
    - username: admin
      password: secret1
    - username: user
      password: pass1
  users:
    - username: admin
      firstName: Felonius
      lastName: Gru
      privileges:
        - VIEW
        - ADMIN
      avatarFile: images/Gru.png
      avatarMimeType: image/png
    - username: user
      firstName: Reed
      lastName: Richards
      privileges:
        - VIEW
      avatarFile: images/Reed.png
      avatarMimeType: image/png
  heroes:
    - name: Dr. Nice
    - name: Bombasto
      rating: 4
    - name: Celeritas
      rating: 5
    - name: Magneta
      rating: 5
    - name: RubberMan
      rating: 5
    - name: Dynama
      rating: 5
    - name: Dr. IQ
    - name: Magma
    - name: Tornado
      rating: 3
